### ISSUE TITLE
Re-Evaluate all AVPs to ensure lack of extensibility is not an issue

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/rfc4006bis#10]
Two issues to date (User-Equipment-Info and Final-Unit-Indication) have required _new_ AVPs due to the fact that they are not extensible.  We need a thorough inventory of those AVPs that are not extensible, i.e. do not have *[AVP] if a Grouped type and determine if a new, corresponding AVP MAY need to be introduced as part of the bis.

**Comment by yuvalif** [comment]
1.  Final-Unit-Indication – already agreed
2.  User-Equipment-Info - already agreed
3.  Redirect-Server – I think we should
4.  Subscription-Id – I think we should
5.  CC-Unit-Type – we can probably skip
6.  Requested-Action - we can probably skip
