### ISSUE TITLE
awkward wording about Final-Unit-Action

### ISSUE THREAD

**Issue by dcdolson** [lbertz02/rfc4006bis#22]
"If the Final-Unit-Action AVP is set to TERMINATE, no other AVPs MUST be present."

As well as being awkward, clearly it is not strictly true, since AVPs about Dest-Host, Orig-Host, etc. must be present.

Perhaps:
"If the Final-Unit-Action AVP is set to TERMINATE, QoS-Final-Unit-Indication group MUST NOT contain any other AVPs."

**Comment by yuvalif** [comment]
agree

**Comment by dcdolson** [comment]
Found a similar issue for Final-Unit-Indication.
Fix in commit e26a63a768f0646dc537170047c64f6ca07989aa
