### ISSUE TITLE
ipv4-mapped-ipv6

### ISSUE THREAD

**Issue by dcdolson** [lbertz02/rfc4006bis#26]
I asked the dime mailing list whether ipv4-mapped-ipv6 addresses should be explicitly permitted.
https://mailarchive.ietf.org/arch/msg/dime/JUGVEEQtMN8aulUNQ-Isu-pwrOk

**Comment by yuvalif** [comment]
dont see any issue with adding this

**Comment by dcdolson** [comment]
Also IPv4-mapped-IPv6 is supported by RFC5952, which we decided as the textual standard.

**Comment by dcdolson** [comment]
Fixed with commit 944356efb9abfdf33104aa119199f95d479c46b1
