### ISSUE TITLE
Using Address type for new AVPs

### ISSUE THREAD

**Issue by dcdolson** [lbertz02/rfc4006bis#27]
I put a question to the dime mailing list asking whether the textual Redirect-Address-IPv4Address and Redirect-Address-IPv6Address should be consolidated into a single Redirect-Address-IPAddress of type Address.
https://mailarchive.ietf.org/arch/msg/dime/t12rUjza5cqrNrRBXrn8TqnkNLw

**Comment by dcdolson** [comment]
If it is decided to keep textual format, the IP AVP types should be changed to OctetString vs. UTF8String.

**Comment by yuvalif** [comment]
i think we can change to the IPAddress type AVPs. also send email on that to the ML

**Comment by dcdolson** [comment]
Fixed with commit 944356efb9abfdf33104aa119199f95d479c46b1
