### ISSUE TITLE
5.6.2 - clarify how different filtering and redirection rules interact

### ISSUE THREAD

**Issue by yuvalif** [lbertz02/rfc4006bis#50]
section 5.6.2, replace existing text with:
"In such a case, the access device MUST treat all packets according to the
Restriction-Filter-Rule AVPs, Filter-Rules AVPs and the rules referred to by
the Filter-Id AVP.  This is in addition to, if possible, redirecting the user to the
destination specified in the Redirect-Server AVP or Redirect-Server-
Extension AVP.”
also need to clarify if remaining traffic gets redirected after applying the filter.

**Comment by lbertz02** [comment]
Will update text as follows:

In such a case, the access device
   MUST treat all packets according to the Restriction-Filter-Rule AVPs,
   Filter-Rules AVPs and the rules referred to by the Filter-Id AVP.
   After treatment is applied according to these rules, all traffic that has
   not been dropped or already forwarded MUST be redirected to the destination
   specified in the Redirect-Server AVP or Redirect-Server-Extension AVP.
