### ISSUE TITLE
mention the section about MAC formatting

### ISSUE THREAD

**Issue by yuvalif** [lbertz02/rfc4006bis#57]
in section 8.54 and 8.50  mention section 3.21 in RFC3580

Q: should the MAC be text or binary?

**Comment by lbertz02** [comment]
From RFC 5777 (setting precedent for us)
The MAC-Address AVP (AVP Code 524) is of type OctetString and
   specifies a single layer 2 address in MAC-48 format.  The value is a
   6-octet encoding of the address as it would appear in the frame
   header.

**Comment by yuvalif** [comment]
User-Equipment-Info-Value (as well as  User-Equipment-Info-MAC) is of type OctetString, so it can have both text and binary values.
but the 3580 reference clearly state that format must be text.
to make sure that we are backward compatible, I suggest that we keep the text format (will add specific section reference to RFC3580) for the existing AVP, and add the reference to RFC5777 to the new AVP?
