### ISSUE TITLE
IPv6 reference is obsolete

### ISSUE THREAD

**Issue by yuvalif** [lbertz02/rfc4006bis#6]
[IPv6Addr]  Hinden, R. and S. Deering, "Internet Protocol Version 6
               (IPv6) Addressing Architecture", RFC 3513, April 2003.
RFC3513 is obsoleted by: https://datatracker.ietf.org/doc/rfc4291/

**Comment by lbertz02** [comment]
- Change RFC4291 to RFC5952

**Comment by yuvalif** [comment]
Section 8.38, the paragraph on Redirect-Address-Type AVP: “The address is a text representation of the address in either the preferred or alternate text form [IPv6Addr].”
[IPv6Addr] refers to obsolete RFC3513. We will change this to RFC5952
As RFC5952 does not mention “preferred” and “alternate” ways, the text in section 8.38 should be modified to: “The address is a text representation of the address according to [RFC5952].”
