### ISSUE TITLE
change "service specific" to "service-specific" 

### ISSUE THREAD

**Issue by yuvalif** [lbertz02/rfc4006bis#61]

**Comment by lbertz02** [comment]
there are 34 instances of "service specific".  Should this be a global change?

**Comment by yuvalif** [comment]
yes, lets do that globally

**Comment by dcdolson** [comment]
I found similar issues with vendor-specific, and other foo-specific cases.

See commit c643f1ae7dd7a60dfaf9aea4461c784fb97f7430
