### ISSUE TITLE
explain AVP in section 1.2

### ISSUE THREAD

**Issue by yuvalif** [lbertz02/rfc4006bis#63]

**Comment by lbertz02** [comment]
I pulled this back in the latest commit.  If this is regarding Eric's comments about expanding AVP in Section 3.1 this was corrected by add the sentence 'The CCR is extensible via the inclusion of one or more Attribute Value Pairs (AVPs).'  The sentence gave us the opportunity to explain the acronym.

**Comment by yuvalif** [comment]
yes. the ask was just to expend the acronym on first use, not to add a full explanation (as it is already in the base)
