### ISSUE TITLE
8.52 and 8.58 - Clarify approach differences

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/rfc4006bis#66]
Section 8.52 =
> >
> > (1) Why do you need to specify the ability to send either the IMEISV or the
> IMEI?
> >
> >> They are distinct structures and the latest generation of networks are
> starting to use IMEISV (with no support for just the IMEI).  However, the
> IMEI value is identical.
> >
> > (2)
> > "If the type of the equipment is one of the
> >   enumerated types of User-Equipment-Info-Type AVP, then the credit-
> >   control client SHOULD send the information in the User-Equipment-Info
> >   AVP, in addition to or instead of the User-Equipment-Info-Extension
> >   AVP."
> >
> > Why is this normative recommendation in support of backwards
> compatibility different from the one given for the Subscription-Id-Extension
> AVP in Sec. 8.58?
> >
> >> It was found that backwards compatibility issues were more prevalent
> with User-Equipment-Info around the IMEISV and some implementations
> can deal with IMEISV and IMEI. The language above is aggressive in
> recommending the "in addition to" in order to maximize compatibility.  8.58 is
> cleaner in terms of its recommendation and production issues have not been
> seen on this AVP so it seemed appropriate to limit the AVP values to one or
> the other and not both as it is for User-Equipment-Info and User-Equipment-
> Info-Extension.
>
> please add some explanatory text to the section.

**Comment by yuvalif** [comment]
IMO, we should not add this meta-information. this is captured in the email archive, if someone want to understand why we chose specific phrasing.

**Comment by lbertz02** [comment]
Added paragraph to 8.52 to address the issue around IMEI.  It states

NOTE, when the IMEISV value is used the credit-control client SHOULD send the
    information in the User-Equipment-Info AVP in addition to the
    User-Equipment-Info-Extension AVP.  This will minimize issues that have been
    observed with production credit control servers.
