### ISSUE TITLE
IMEI and IMEISV (WG List Discussion)

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/rfc4006bis#9]
- Currently only IMEISV is mentioned in the list of User-Equipment-Info-Type list 
- Upon investigation realized that User-Equipment-Info-Type  was
  - Not extensible
  - Uses an enumeration for type and a string for data storage
  - Implication: Adding IMEI support requires an ENUM extension which creates a new Diameter Application ID (see Guidelines)
- Proposal : New AVP User-Equipment (Grouped Type) that 
  - includes 4 new AVPs (for each equipment type)
  - is extensible

**Comment by yuvalif** [comment]
will be addressed in: https://github.com/lbertz02/rfc4006bis/issues/15
